[package]
name = "face"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ort = "2.0.0-rc.1"
image = "0.25.1"
ndarray = "0.15.6"
hyper = "1.3.1"
rayon = "1.10.0"